name: smart_academy
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4  # يمكنك تحديث هذا إلى ^3.7.0 إذا كنت تستخدم Flutter 3.19+

dependencies:
  flutter:
    sdk: flutter

  # حزم Firebase المحدثة
  firebase_core: ^3.14.0
  firebase_storage: ^12.4.7
  google_sign_in: ^6.2.3  # أحدث إصدار
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  url_launcher: ^6.2.5  # (الإصدار الحالي هو الأحدث)

  # حزم مساعدة
  loading_indicator: ^3.1.1
  fluttertoast: ^8.2.12  # (الإصدار الحالي هو الأحدث)
  flutter_bloc: ^9.1.1

  # حزم تحتاج تحديثات رئيسية
  flutter_slidable: ^4.0.0  # تحديث رئيسي
  image_picker: ^1.1.2     # تحديث رئيسي
  intl: ^0.20.2           # تحديث رئيسي
  uuid: ^4.0.0            # (الإصدار الحالي هو الأحدث)

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0   # أو 6.0.0 إذا كنت تستخدم Flutter 3.19+

flutter:
  uses-material-design: true

  assets:
    - assets/image/google-symbol.png
    - assets/image/empty.png
    - assets/image/