// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4N1iSN4ELbbBGBQ28vVxuh4wdD8wW2sM',
    appId: '1:488099238193:web:6b3696be085d42cb37e010',
    messagingSenderId: '488099238193',
    projectId: 'smartacademy-61836',
    authDomain: 'smartacademy-61836.firebaseapp.com',
    storageBucket: 'smartacademy-61836.firebasestorage.app',
    measurementId: 'G-XKY9W1W66G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-FGV_v1chrR6ehPYs8I9lURKWibYM5kk',
    appId: '1:488099238193:android:db795f458f1fa2ea37e010',
    messagingSenderId: '488099238193',
    projectId: 'smartacademy-61836',
    storageBucket: 'smartacademy-61836.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-j8osqLn6cO5M8m13X-0Z2SR0J-Sqqtk',
    appId: '1:488099238193:ios:a57fd32625c85f3037e010',
    messagingSenderId: '488099238193',
    projectId: 'smartacademy-61836',
    storageBucket: 'smartacademy-61836.firebasestorage.app',
    iosBundleId: 'com.example.smartAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-j8osqLn6cO5M8m13X-0Z2SR0J-Sqqtk',
    appId: '1:488099238193:ios:a57fd32625c85f3037e010',
    messagingSenderId: '488099238193',
    projectId: 'smartacademy-61836',
    storageBucket: 'smartacademy-61836.firebasestorage.app',
    iosBundleId: 'com.example.smartAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4N1iSN4ELbbBGBQ28vVxuh4wdD8wW2sM',
    appId: '1:488099238193:web:c1bf8bd757a9397537e010',
    messagingSenderId: '488099238193',
    projectId: 'smartacademy-61836',
    authDomain: 'smartacademy-61836.firebaseapp.com',
    storageBucket: 'smartacademy-61836.firebasestorage.app',
    measurementId: 'G-98XTK0Q2FS',
  );
}
